[package]
name = "castly"
version = "0.7.1"
edition = "2021"

[dependencies]
# Error handling
thiserror = "2.0.17"

# Async traits
async-trait = "0.1.89"

# API
axum = "0.8.6"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"

# Async consumer
rdkafka = { version = "0.38.0", features = ["cmake-build"] }

# Asynchronous tasks
tokio = { version = "1.42", features = ["full"] }
tokio-stream = "0.1.17"

# Config from yaml or configmap
config = "0.15.18"
serde_yaml = "0.9.34+deprecated"

# HTTP calls
reqwest = { version = "0.12.23", features = ["json"] }

# Logging
tracing = "0.1"
tracing-subscriber = "0.3.20"

# Template
tera = "1.0"

[dev-dependencies]
# Testing
tokio-test = "0.4"
tempfile = "3.23.0"
